
@baseUrl = http://localhost:3000

#RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=10
# &user=elias

### Lista apenas um recado
GET {{baseUrl}}/recados/3/

### Criar um recado
POST  {{baseUrl}}/recados/
Content-Type: application/json

  {
    "texto": "Novo teste",
    "de": "Joana",
    "para": "joãos"
  }

### Atualiza um recado
PATCH  {{baseUrl}}/recados/7/
Content-Type: application/json

  {
      "texto": "teste de textossss"
  }


### Apaga um recado
DELETE  {{baseUrl}}/recados/3/

### AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}/


### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoCOntrollerHome

GET {{baseUrl}}/conceitos-automatico

### chamando methodo do service Home

# @name ConceitosServiceExemplo

GET {{baseUrl}}/exemplo