
@baseUrl = http://localhost:3000

#RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=10
# &user=elias

### Lista apenas um recado
GET {{baseUrl}}/recados/4/

### Criar um recado
POST  {{baseUrl}}/recados/
Content-Type: application/json

  {
    "texto": "Novo Recado1sssss",
    "de": "Joana",
    "para": "joão",
    "lido": false,
    "data": "2024-10-17T15:29:32.440Z"
  }

### Atualiza um recado
PATCH  {{baseUrl}}/recados/2/
Content-Type: application/json

  {
      "texto": "Novo Recado atualizado",
      "de": "Joana",
      "para": "joão",
      "lido": false,
      "data": "2024-10-17T15:29:32.440Z"
  }

### Apaga um recado
DELETE  {{baseUrl}}/recados/2/

### AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}/


### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoCOntrollerHome

GET {{baseUrl}}/conceitos-automatico

### chamando methodo do service Home

# @name ConceitosServiceExemplo

GET {{baseUrl}}/exemplo